### ISSUE TITLE
Refactor Data Management for REM

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/eea-recurring-events-manager#11]
- initially built using a Redux style pattern but with the previous JS models from core ( see: https://github.com/eventespresso/eea-recurring-events-manager/tree/master/assets/src/data-stores)

- will need GQL type(s) added server side for the `recurrence` table, which should the following definition (SQL):

```sql
RCR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
RCR_pattern_hash varchar(50) NOT NULL,
RCR_rRule text NOT NULL,
RCR_exRule text DEFAULT NULL,
RCR_rDates text DEFAULT NULL,
RCR_exDates text DEFAULT NULL,
RCR_sales_start_offset text DEFAULT NULL,
RCR_sales_end_offset text DEFAULT NULL,
PRIMARY KEY  (RCR_ID)'
```

example data:

```
RCR_ID: 1234
RCR_pattern_hash: "cjld2cyuq0000t3rmniod1foy"
RCR_rRule: "DTSTART:20200701T070000Z;RRULE:FREQ=MONTHLY;INTERVAL=1;BYSETPOS=-1;BYDAY=FR;UNTIL=20201231T080000Z"
RCR_exRule: "DTSTART:20200701T070000Z;RRULE:FREQ=MONTHLY;INTERVAL=1;BYSETPOS=-1;BYDAY=FR;UNTIL=20201231T080000Z"
RCR_rDates: "20200827T070000Z,20201029T070000Z"
RCR_exDates: "20201225T080000Z"
RCR_sales_start_offset: "1 month before start"
RCR_sales_end_offset: "2 hours before end"
```

- EEM_Datetime also has a new `RCR_ID` field and relation added to the above table which will need to be accommodated for, preferably without making any changes to core.

#### PHP:
recurrence child class equivalents of:

- [ ] `EventEspresso\RecurringEvents\domain\entities\admin\GraphQLData\Recurrences` 

- [ ] `EventEspresso\RecurringEvents\domain\services\admin\entities\DefaultRecurrence` 

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\connection_resolvers\RecurrenceConnectionResolver`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\connections\DatetimeRecurrencesConnection`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\data\loaders\RecurrenceLoader`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\data\mutations\RecurrenceMutation`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\mutators\RecurrenceCreate`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\mutators\RecurrenceDelete`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\mutators\RecurrenceUpdate`

- [ ] `EventEspresso\RecurringEvents\domain\services\graphql\types\Recurrence`

#### JS/TS:

- [ ] `assets/src/data/services/apollo/queries/recurrences/useRecurrenceQuery.ts`

- [ ] `assets/src/domain/services/apollo/mutations/recurrences/useRecurrenceMutator.ts`

- [ ] `assets/src/domain/services/apollo/mutations/recurrences/useOnCreateRecurrence.ts`

- [ ] `assets/src/domain/services/apollo/mutations/recurrences/useOnDeleteRecurrence.ts`

- [ ] `assets/src/domain/services/apollo/mutations/recurrences/useOnUpdateRecurrence.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydration.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/mutations/recurrences/useUpdateRecurrenceCache.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/mutations/recurrences/useUpdateRelatedDatetimes.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/mutations/recurrences/useOptimisticResponse.ts` ???

- [ ] `assets/src/domain/eventEditor/services/apollo/queries/recurrences/useRecurrences.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/queries/recurrences/useFetchRecurrences.ts`

- [ ] `assets/src/domain/eventEditor/services/apollo/queries/recurrences/useRelatedRecurrences.ts` ???

- [ ] `???`

**Comment by manzoorwanijk** [comment]
> `EEM_Datetime` also has a new `RCR_ID` field and relation added to the above table

This confuses me. Does that mean `RCR_ID` field is added to Datetime table?
