### ISSUE TITLE
Add Capabilities Restrictions

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/eea-recurring-events-manager#45]
For Event Smart we will need to restrict access to REM to only those users that subscribe to that functionality.

Is there a set schema for defining capabilities for Event Smart or are they simply created on the fly as needed?

I'm guessing we might want something like:

```
ee_recurring_events_manager
ee_read_default_recurring_date
ee_read_default_recurring_dates
ee_read_others_default_recurring_dates
ee_edit_default_recurring_date
ee_edit_default_recurring_dates
ee_delete_default_recurring_date
ee_delete_default_recurring_dates
ee_delete_others_default_recurring_dates
```

thoughts?

**Comment by garthkoyle** [comment]
You're on the right track. REM capabilities will be new to Event Smart because we don't have that feature on Event Smart yet.

**Comment by tn3rb** [comment]
closing because this has been done via other PRs
