### ISSUE TITLE
Fix Uncaught Error: Cannot call constructor in \eea-recurring-events-manager\domain\services\graphql\connections\RootQueryRecurrencesConnection.php on line 29

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/eea-recurring-events-manager#56]
Loading the latest version of `dev` brach throws this fatal:

```
( ! ) Fatal error: Uncaught Error: Cannot call constructor in C:\laragon\www\ee4editor\wp-content\plugins\eea-recurring-events-manager\domain\services\graphql\connections\RootQueryRecurrencesConnection.php on line 29
Error: Cannot call constructor in C:\laragon\www\ee4editor\wp-content\plugins\eea-recurring-events-manager\domain\services\graphql\connections\RootQueryRecurrencesConnection.php on line 29
```

If I switch to mater (which isn't far behind) it's fine. Looks like its from this change:

https://github.com/eventespresso/eea-recurring-events-manager/commit/4f9b3f7429367fb3dfcdde32581e0b655ec55738#diff-4d862c80fba00bd5cf3f13c6425b16ba8d411d94e8e24fe611e266a01ae9a316R29

Latest version of EE4 REM - Dev
Latest version of EE4 Core - Dev Stable

With both active, try to create a new event and you'll get the above error.

**Comment by Pebblo** [comment]
Just to note, I switch the above back to what it had before that commit (just the single line I linked to) and the editor loads but no REM features (or any datetime/ticket features) but there's a new fatal:

`
( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to EventEspresso\RecurringEvents\domain\services\graphql\mutators\RecurrenceUpdate::mutateAndGetPayload() must be an instance of EEM_Recurrence, null given, called in C:\laragon\www\ee4editor\wp-content\plugins\eea-recurring-events-manager\domain\services\graphql\types\Recurrence.php on line 123 and defined in C:\laragon\www\ee4editor\wp-content\plugins\eea-recurring-events-manager\domain\services\graphql\mutators\RecurrenceUpdate.php on line 24
`

Not sure if that's related to the above changes again or need a new ticket?

**Comment by manzoorwanijk** [comment]
It's because Core `dev-stable` is behind `FET/reg-form-builder/main` which contains the latest code/types which are used/mapped in REM `dev`. So, if you switch to `FET/reg-form-builder/main`, it should work just fine.

**Comment by tn3rb** [comment]
we'll need to either:

- copy updates for code/types over to `dev-stable` (hackey band-aid fix)

- fix `FET/reg-form-builder/main` so that any half baked code is hidden behind some sort of Feature Flag so that its changes don't break existing functionality (preferable but more complex fix)

**Comment by tn3rb** [comment]
closing because this would no longer be a valid issue
